name: 'Azure Blob Upload'
description: 'A simple helper that will upload all the files in a source path to a destination path in a Blob container.'
author: 'Lance McCarthy'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  connection_string:
    description: 'Azure Storage ConnectionString for the container (Azure Portal - select Storage Account - Access Keys blade).'
    required: true
  container_name:
    description: 'Blob Container name (e.g. my-container).'
    required: true
  source_folder:
    description: 'The local folder containing all the files and subfolders to upload to the blob container (use a trailing slash).'
    required: true
  destination_folder:
    description: 'The target folder to use in the blob container with (do not use a leading or trailing slash).'
    required: false
  clean_destination_folder:
    description: 'This option will delete all the blobs in destination_folder before uploading the new files.'
    required: false
    default: false
  fail_if_source_empty:
    description: 'If you want the Action to fail and report an error if the source_folder is empty.'
    required: false
    default: false
  is_recursive:
    description: 'Set to false if you want all subfolders ignored.'
    required: false
    default: true
  delete_if_exists:
    description: 'If the blob exists it will be skipped, unless this is set to true.'
    required: false
    default: false

runs:
  using: 'node20'
  main: 'dist/index.js'
