name: 'Azure Blob Upload'
description: 'A simple helper that will upload all the files in a source path to a destination path in a Blob container.'
author: 'Lance McCarthy'
branding:
  icon: 'upload-cloud'  # https://feathericons.com/
  color: 'purple'
inputs:
  connection_string:
    description: 'Azure Storage ConnectionString for the container (Azure Portal > select Storage Account > Access Keys blade).'
    required: true
  container_name:
    description: 'Blob container name'
    required: true
  source_path:
    description: 'The folder containing all the files you want to upload.'
    required: true
    default: './'
  destination_folder:
    description: 'Any desintation path (i.e. subfolder) in the blob container.'
    required: false
    default: 'MySubFolder'
  clean_destination_folder:
    description: 'This option will delete all the blobs in destination_folder (default is false).'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions