name: 'Issue Investigations'

on:
  push:
    branches:
      - 'issue-investigation/*'

jobs:
  # Build, package and run Jest tests
  Package_RunTests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run rebuild
          npm run format
          npm run lint
          npm run package
          npm test
  
  # Confirm the Action works on a clean machine without building
  Upload_Test: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generating Unique File Names for This Run
        run: |
          $date = Get-Date -Format "yyyy.Mdd.hh.mm"
          
          $parentFilePath = 'TestFiles\TxtFiles\Parent.txt'
          $updatedParentFileName = "Parent_" + $date + ".txt"
          Rename-Item $parentFilePath $updatedParentFileName
          
          $childFilePath = 'TestFiles\TxtFiles\Subfolder\Child.txt'
          $updatedChildFileName = "Child_" + $date + ".txt"
          Rename-Item $childFilePath $updatedChildFileName

          $excelFilePath = 'TestFiles\ExcelFiles\Test.xlsx'
          $updatedExcelFileName = "Test_" + $date + ".xlsx"
          Rename-Item $excelFilePath $updatedExcelFileName

      # NOTE: this job also cleans the entire container to start over for this round of tests
      - name: Upload without DestinationFolder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\ExcelFiles\
          clean_destination_folder: true

      - name: Recursive with DestinationFolder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\TxtFiles\
          destination_folder: RecursiveTest
          clean_destination_folder: true
      
      - name: Non-recursive with Destination Folder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\TxtFiles\
          destination_folder: NonRecursiveTest
          clean_destination_folder: true
          is_recursive: false
        
      - name: Non-recursive with Destination Folder Test (with '.' Prefix)
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\TestFiles\ExcelFiles\
          destination_folder: DotPrefixTest
          clean_destination_folder: true
          is_recursive: false

      - name: Single File Path Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\build\bin\data-composer-0.0.0.exe
          destination_folder: SingleFileTest
          clean_destination_folder: true
          is_recursive: false
      
      - name: Single File Test (with '.' Prefix)
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\TestFiles\build\bin\data-composer-0.0.0.exe
          destination_folder: SingleFileWithPrefixTest
          clean_destination_folder: true
          is_recursive: false
