name: 'Issue Investigations'

on:
  push:
    branches:
      - 'issue-investigation/*'

jobs:
  # Build, package and run Jest tests
  Package_RunTests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
          npm run package
          npm test
  
  # Confirm the Action works on a clean machine without building
  Upload_Test: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generating Unique File Names for This Run
        run: |
          $date = Get-Date -Format "yyyy.Mdd.hh.mm"
          
          $parentFilePath = 'src\TestData\TextFileTestRoot\Parent.txt'
          $updatedParentFileName = "Parent_" + $date + ".txt"
          Rename-Item $parentFilePath $updatedParentFileName
          
          $childFilePath = 'src\TestData\TextFileTestRoot\Subfolder\Child.txt'
          $updatedChildFileName = "Child_" + $date + ".txt"
          Rename-Item $childFilePath $updatedChildFileName

          $excelFilePath = 'src\TestData\ExcelFileTestRoot\Test.xlsx'
          $updatedExcelFileName = "Test_" + $date + ".xlsx"
          Rename-Item $excelFilePath $updatedExcelFileName

      - name: Upload Excel file without DestinationFolder
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: src\TestData\ExcelFileTestRoot\
          clean_destination_folder: true

      - name: Upload Text Files with DestinationFolder
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: src\TestData\TextFileTestRoot\
          destination_folder: TextFilesTest
          clean_destination_folder: true
      
      - name: Upload Text Files Non-recursive
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: src\TestData\TextFileTestRoot\
          destination_folder: NonRecursiveTest
          clean_destination_folder: true
          is_recursive: false
      
      - name: Upload folder with dot Prefix
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\src\TestData\ExcelFileTestRoot\
          destination_folder: DotPrefixFolderTest
          clean_destination_folder: true
          is_recursive: false

      - name: Upload file with dot Prefix
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\src\TestData\ExcelFileTestRoot\Test.xlsx
          destination_folder: DotPrefixFileTest
          clean_destination_folder: true
          is_recursive: false
