name: 'Issue Investigations'

on:
  push:
    branches:
      - 'issue-investigation/*'
      - '[0-9]+-*'

jobs:
  # Build, package and run Jest tests
  Package_RunTests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: "Run scripts"
        run: npm run all
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"


  LargeFileCount_Test:
    name: Publish wwwroot using Windows
    runs-on: windows-latest
    needs: Package_RunTests
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: Upload wwwroot to /LargeFileCountTest/Windows
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          destination_folder: LargeFileCountTest/Windows
          source_folder: TestFiles\wwwroot\
          clean_destination_folder: true


  # Confirm the Action works on a clean machine without building
  Upload_Test: 
    runs-on: windows-latest
    needs: LargeFileCount_Test
    steps:
      - uses: actions/checkout@v4

      - name: Generating Unique File Names for This Run
        run: |
          $date = Get-Date -Format "yyyy.Mdd.hh.mm"
          
          $parentFilePath = 'TestFiles\TxtFiles\Parent.txt'
          $updatedParentFileName = "Parent_" + $date + ".txt"
          Rename-Item $parentFilePath $updatedParentFileName
          
          $childFilePath = 'TestFiles\TxtFiles\Subfolder\Child.txt'
          $updatedChildFileName = "Child_" + $date + ".txt"
          Rename-Item $childFilePath $updatedChildFileName

          $excelFilePath = 'TestFiles\ExcelFiles\Test.xlsx'
          $updatedExcelFileName = "Test_" + $date + ".xlsx"
          Rename-Item $excelFilePath $updatedExcelFileName

      # NOTE: this job also cleans the entire container to start over for this round of tests
      - name: Upload without DestinationFolder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\ExcelFiles\
          clean_destination_folder: true

      - run: Start-Sleep -Seconds 2

      - name: Recursive with DestinationFolder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\TxtFiles\
          destination_folder: RecursiveTest
          clean_destination_folder: true

      - run: Start-Sleep -Seconds 2

      - name: Non-recursive with Destination Folder Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\TxtFiles\
          destination_folder: NonRecursiveTest
          clean_destination_folder: true
          is_recursive: false

      - run: Start-Sleep -Seconds 2

      - name: Non-recursive with Destination Folder Test (with '.' Prefix)
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\TestFiles\ExcelFiles\
          destination_folder: DotPrefixTest
          clean_destination_folder: true
          is_recursive: false

      - run: Start-Sleep -Seconds 2

      - name: Single File Path Test
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: TestFiles\build\bin\data-composer-0.0.0.exe
          destination_folder: SingleFileTest
          clean_destination_folder: true
          is_recursive: false

      - run: Start-Sleep -Seconds 2

      - name: Single File Test (with '.' Prefix)
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: .\TestFiles\build\bin\data-composer-0.0.0.exe
          destination_folder: SingleFileWithPrefixTest
          clean_destination_folder: true
          is_recursive: false
