name: 'Issue Investigations'

on:
  push:
    branches:
      - 'issue-investigation/*'

jobs:
  # Build, package and run Jest tests
  Package_RunTests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
          npm run package
          npm test
  
  # Confirm the Action works on a clean machine without building
  Upload_Test: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generating Unique File Names for This Run
        run: |
          $date = Get-Date -Format "yyyy.Mdd.hh.mm"
          
          $parentFilePath = 'src\TestData\TextFileTestRoot\Parent.txt'
          $updatedParentFileName = "Parent_" + $date + ".txt"
          Rename-Item $parentFilePath $updatedParentFileName
          
          $childFilePath = 'src\TestData\TextFileTestRoot\Subfolder\Child.txt'
          $updatedChildFileName = "Child_" + $date + ".txt"
          Rename-Item $childFilePath $updatedChildFileName

          $excelFilePath = 'src\TestData\ExcelFileTestRoot\Test.xlsx'
          $updatedExcelFileName = "Test_" + $date + ".xlsx"
          Rename-Item $excelFilePath $updatedExcelFileName

      - name: Upload Excel file without Destination Folder
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: src\TestData\ExcelFileTestRoot\
          clean_destination_folder: true

      - name: Upload Text Files with Destination Folder
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_folder: src\TestData\TextFileTestRoot\
          destination_folder: MyTargetFolder
          clean_destination_folder: true
