name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          npm run package
      - run: |
          npm test

  test: # make sure the action works on a clean machine without building
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      # Create unique test file so that we can verify the upload was successful for this specific run.
      - uses: Amadevus/pwsh-script@v1
        name: Generating File Name and Data
        id: PwrShell
        with:
          script: |
            $date = Get-Date -Format "yyyy.Mdd.hh.mm"
            $parentUpdatedFileName = "Parent_" + $GITHUB_RUN_NUMBER + ".txt"
            Rename-Item src\TestContent\ParentHelloWorld.txt $parentUpdatedFileName
            $childUpdatedFileName = "Child_" + $GITHUB_RUN_NUMBER + ".txt"
            Rename-Item src\TestContent\MySubFolder\ChildHelloWorld.txt $childUpdatedFileName
        
      - name: Azure Blob Upload
        uses: ./
        with:
          connection_string: ${{ secrets.AzureBlobConnectionString }}
          container_name: ci-cd
          source_path: src\TestContent\
          destination_path: AzureBlobUploadAction
          clean_destination_path: true
